export const RECEIVE_POSITION = 'receive_position'
export const RECEIVE_CATEGORY = 'receive_category'
export const RECEIVE_SHOPS = 'receive_shops'
export const RECEIVE_USER_INFO = 'receive_user_info'
export const RESET_USER_INFO = 'reset_user_info'
